name: Deploy site files

on:
  push:
    branches:
      - sourcecode # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE
  pull_request:
    branches:
      - sourcecode # 只在master上push触发部署
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: |
          npm i
      - name: Build
        run: |
          npm run build
          cp README.md docs/.vuepress/dist/
          cd docs/.vuepress/dist
      - name: Git init
        run: |
          git config --global user.name 'godbasin'
          git config --global user.email 'wangbeishan@163.com'
          git init
      - name: Git Add and Commit
        run: |
          git add -A
          git commit -m 'deploy'
      - name: Git Remote Add
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git remote add origin https://github.com/front-end-fighting/front-end-world.git
      - name: Git Push
        run: |
          git push origin master -f
